data = [
    "http://www.careeronestop.org/",
    "https://cew.georgetown.edu/cew-reports/competencies/",
    "http://www.mynextmove.org/",
    "http://www.onetcenter.org/",
    "http://www.jobhuntersbible.com/",
    "http://www.asktheheadhunter.com/",
    "http://www.best-job-interview.com/",
    "http://www.bbb.org/",
    "http://www.bls.gov/oco",
    "http://money.cnn.com/news/economy/index.html",
    "http://www.cvtips.com/",
    "http://www.dol.gov/",
    "http://www.ebri.org/",
    "http://www.glassdoor.com/index.htm",
    "http://www.guidestar.org/",
    "http://www.linkedin.com/",
    "http://www.jobsearchintelligence.com/NACE/salary-calculator-intro/",
    "http://www.salary.com/",
    "http://www.sec.gov/",
    "http://www.dresstoachieve.com/index.htm",
    "http://jobmarket.nytimes.com/pages/jobs",
    "https://americorps.gov/",
    "http://www.newyorkcares.org/",
    "http://www.nycservice.org/search/",
    "http://aftercollege.com/",
    "http://www.barefootstudent.com/",
    "http://www.collegerecruiter.com/",
    "http://collegegrad.com/",
    "http://www.aam-us.org/",
    "http://www.artsusa.org/",
    "http://www.artcurators.org/",
    "http://www.bookjobs.com/",
    "http://www.ed2010.com/",
    "http://www.entertainmentcareers.net/",
    "http://newyork.fgi.org/",
    "http://www.journalismjobs.com/",
    "https://www.mandy.com/",
    "http://www.marketingjobs.com/",
    "http://www.mediabistro.com/",
    "http://www.arts.gov/",
    "http://nyfa.org/",
    "http://www.nyc.gov/html/dcla/html/home/home.shtml",
    "http://www.nyc.gov/html/film/html/index/index.shtml",
    "http://talenthouse.com/",
    "https://diversebooks.org/",
    "http://www.afterschoolpathfinder.org/",
    "http://www.charterschooljobs.com/Default.aspx",
    "http://chronicle.com/section/Jobs/61/",
    "http://www.topschooljobs.org/",
    "http://higheredjobs.com/",
    "http://www.hunter.cuny.edu/education/",
    "http://www.hunter.cuny.edu/school-of-education/current-students/job-placement/overview",
    "http://www.isaagny.org/index.aspx",
    "http://www.insidehighered.com/",
    "http://insideschools.org/",
    "http://www.lacnyc.org/jobs-board",
    "http://www.mathforamerica.org/web/guest/home",
    "http://www.nycteachingfellows.org/",
    "http://www.olasjobs.org/",
    "http://www.teachforamerica.org/",
    "http://schools.nyc.gov/teachnyc/",
    "http://teachers-teachers.com/",
    "http://www.schoolspring.com/",
    "http://steinhardt.nyu.edu/research_alliance/",
    "http://www.schoolspring.com/",
    "http://studentaffairs.com/",
    "http://www.healthecareers.com/",
    "http://www.allhealthcarejobs.com/",
    "http://biospace.com/",
    "http://www.wehealny.org/",
    "http://www.health.ny.gov/professionals/ems/educ.htm",
    "http://explorehealthcareers.org/",
    "http://www.healthecareers.com/",
    "http://www.hospitaljobsonline.com/",
    "http://www.medicare.gov/hospitalcompare/search.html",
    "http://www.hunter.cuny.edu/schoolhp/",
    "http://www.medopportunities.com/",
    "http://nypta.associationcareernetwork.com/Common/HomePage.aspx",
    "http://www.nyc.gov/html/hhc/html/home/home.shtml",
    "http://www.health.ny.gov/",
    "http://www.pharmacychoice.com/",
    "http://www.ptjobs.com/",
    "http://www.rxcareercenter.com/",
    "http://www.scribeamerica.com/",
    "http://www.investopedia.com/university/financial-careers/",
    "http://www.accountingjobstoday.com/",
    "http://www.accountingtoday.com/",
    "http://bankjobs.com/",
    "http://www.beanactuary.com/",
    "http://www.careerjournal.com/",
    "http://www.careers-in-business.com/",
    "http://www.careers-in-finance.com/",
    "http://efinancialcareers.com/",
    "http://finance.google.com/finance",
    "http://www.mergersandinquisitions.com/",
    "https://www.thiswaytocpa.com/",
    "http://finance.yahoo.com/",
    "http://careers.findlaw.com/",
    "http://www.legalstaff.com/",
    "http://www.nycbar.org/index.htm",
    "http://www.nycla.org/",
    "http://www.newyorklawjournal.com/careers.jsp",
    "http://www.nalp.org/",
    "http://www.nyc.gov/dcas",
    "https://www1.nyc.gov/jobs/explore-careers.page",
    "http://home.nyc.gov/",
    "http://www.ny.gov/",
    "http://www.cs.ny.gov/pco/",
    "http://www.ny.gov/",
    "http://www.cs.ny.gov/testing/testguides.cfm",
    "http://www.cs.ny.gov/announ/emaillist.cfm",
    "http://www.statelocalgov.net/",
    "http://www.americorps.gov/Default.asp",
    "http://www.pse-net.com/",
    "http://www.jobsfed.com/",
    "http://www.governmentjobs.com/",
    "http://www.makingthedifference.org/index.shtml",
    "http://www.nffe.org/ht/d/Home/pid/175",
    "https://www.usajobs.gov/StudentsAndGrads",
    "http://www.rcjobs.com/",
    "http://www.federaltimes.com/",
    "http://www.commerce.gov/",
    "http://www.dhs.gov/",
    "http://www.hud.gov/",
    "http://www.dol.gov/",
    "http://www.state.gov/",
    "http://www.ustreas.gov/",
    "http://www.epa.gov/",
    "http://www.eeoc.gov/",
    "http://www.fbi.gov/",
    "http://www.fcc.gov/",
    "http://www.fdic.gov/",
    "http://www.irs.gov/",
    "http://www.opm.gov/",
    "http://www.usa.gov/",
    "http://www.idealist.org/",
    "http://www.careersinfood.com/",
    "http://www.coalitionny.org/jobs/",
    "http://www.fpa.org/",
    "http://goodfoodjobs.com/",
    "http://nccs.urban.org/",
    "http://www.philanthropy.com/jobs",
    "http://www.thenonprofittimes.com/",
    "http://eoffice.nonprofitstaffing.com/jobboard/search/",
    "http://www.publicservicecareers.org/",
    "http://www.ynpn.org/",
    "http://www2.guidestar.org/",
    "http://www.un.org/en/employment/",
    "http://www.unionjobs.com/",
    "http://www.vera.org/",
    "http://www.aiha.org/Pages/default.aspx",
    "http://www.aiha.org/Content/CES/CES.htm",
    "http://www.acm.org/",
    "http://cewd.org/",
    "http://www.computerjobs.com/",
    "http://www.connectionsny.com/",
    "http://www.dice.com/",
    "http://www.floridahightech.com/",
    "http://www.gridleydigitalny.com/",
    "http://www.nycseed.com/",
    "http://sciencecareers.sciencemag.org/",
    "http://www.sciencejobs.org/",
    "http://www.sciencejobs.com/",
    "http://www.careercornerstone.org/",
    "http://www.topresearchjobs.com/",
    "http://www.care2.com/",
    "http://www.cunysustainablecities.org/",
    "http://environmentalcareer.com/",
    "http://www.greenbiz.com/",
    "http://greencareerguide.jobthread.com/",
    "http://www.nwf.org/",
    "http://www.naaee.org/",
    "http://www.nyc.gov/html/planyc2030/html/home/home.shtml",
    "http://www.treehugger.com/",
    "http://www.nabainc.org/",
    "http://www.nafeonation.org/",
    "http://nsbe.org/",
    "http://diversityemployers.com/",
    "http://www.ascendleadership.org/",
    "http://www.apanet.org/",
    "http://www.adata.org/",
    "http://www.business-disability.com/",
    "http://www.dol.gov/odep",
    "http://www.hacu.net/",
    "http://www.latinosforhire.com/",
    "http://www.nshmba.org/",
    "http://www.sacnas.org/",
    "http://www.shpe.org/",
    "http://www.upwardlyglobal.org/",
    "http://www.reserveinc.org/",
    "http://www.dol.gov/vets/ahaw/",
    "http://www.dol.gov/vets/",
    "http://www.military.com/careers",
    "http://taonline.com/",
    "http://www.dol.gov/vets",
    "http://www.vetjobs.com/",
    "http://www.awis.org/",
    "http://www.webgrrls.com/",
    "http://womenforhire.com/",
    "http://www.womensforum.com/",
    "http://www.acatcredentials.org/",
    "http://www.aacsb.edu/",
    "http://www.aba.com/default.htm",
    "http://www.aicpa.org/Pages/Default.aspx",
    "http://www.aswa.org/",
    "http://www.afponline.org/",
    "http://www.casact.org/",
    "http://www.theiia.org/",
    "http://www.imanet.org/",
    "http://www.internationalaccountingbulletin.com/",
    "http://www.iaqf.org/",
    "http://www.internationalinsuranceprofessionals.org/",
    "http://www.nabainc.org/",
    "http://nasba.org/",
    "http://www.nsacct.org/",
    "http://www.nyssa.org/",
    "http://www.nysscpa.org/",
    "http://www.nonprofitcpas.com/",
    "http://www.sifma.org/",
    "http://www.soa.org/",
    "http://www.adminsecret.com/",
    "http://www.amanet.org/",
    "http://www.theaeap.com/",
    "http://www.iaap-hq.org/",
    "http://www.humanresources.org/",
    "http://www.naceweb.org/",
    "http://www.nehra.com/",
    "http://www.opeiu.org/",
    "http://www.recruitersnetwork.com/index.htm",
    "http://www.shrm.org/",
    "http://adage.com/",
    "http://www.aaf.org/",
    "http://www.marketingpower.com/",
    "http://www.the-dma.org/index.php",
    "http://www.marketingedge.org/",
    "http://www.oneclub.org/",
    "http://advamed.org/",
    "http://www.aapa.org/",
    "http://www.acha.org/",
    "http://www.eatright.org/",
    "http://www.aha.org/aha_app/index.jsp",
    "http://www.ama-assn.org/",
    "http://www.aota.org/",
    "http://www.pharmacist.com/",
    "http://www.apha.org/",
    "http://www.ashaweb.org/",
    "http://www.asha.org/default.htm",
    "http://www.ascp.org/default.aspx",
    "http://www.gnyha.org/1/Default.aspx",
    "http://www.nanp.org/",
    "http://www.nypta.org/",
    "http://www.osha.gov/",
    "http://nyspha.roundtablelive.org/",
    "http://www.sophe.org/",
    "http://www.aibs.org/",
    "http://www.aaas.org/",
    "http://www.asm.org/",
    "http://www.nabt.org/",
    "http://www.asm.org/",
    "http://www.aaas.org/",
    "http://www.acs.org/",
    "http://www.theaic.org/",
    "http://www.asbmb.org/",
    "http://www.nsta.org/",
    "http://www.setac.org/",
    "http://www.apsac.org/",
    "http://www.cec.sped.org/",
    "http://www.fccanys.org/",
    "http://www.naccp.org/",
    "http://www.naeyc.org/",
    "http://www.nccanet.org/",
    "http://www.zerotothree.org/",
    "http://www.aaja.org/",
    "http://www.cencom.org/",
    "http://www.cwa-union.org/",
    "http://http//www.iatse-intl.org/",
    "http://www.iatse-intl.org/",
    "http://www.irts.org/",
    "http://www.magazine.org/",
    "http://www.nabj.org/",
    "http://www.nabetcwa.org/",
    "http://www.nab.org/",
    "http://www.nahj12.com/",
    "http://www.natcom.org/nca/Template2.asp?sid=9",
    "http://www.natcom.org/",
    "http://www.naa.org/",
    "http://www.nywici.org/",
    "http://www.prsa.org/",
    "http://www.aitp.org/",
    "http://www.meetup.com/CUNY-Tech-Meetup/",
    "http://www.theesa.com/",
    "http://www.icep.org/",
    "http://www.igda.org/",
    "http://www.iteea.org/",
    "http://nytech.org/",
    "http://www.acjs.org/",
    "http://www.corrections.com/aca",
    "http://www.asc41.com/",
    "http://www.fleoa.org/",
    "http://www.ncja.org/",
    "http://www.sheriffs.org/",
    "http://www.vanderbilt.edu/AEA/",
    "http://www.marketingpower.com/",
    "http://www.nabe.com/",
    "http://www.councilforeconed.org/",
    "https://financialresearch.gov/",
    "http://www.aaup.org/aaup",
    "http://www.aera.net/",
    "http://www.aft.org/",
    "http://www.ala.org/index.cfm",
    "http://www.ncea.org/",
    "http://www.nea.org/",
    "http://www.nysais.org/",
    "http://www.actorsequity.org/home.asp",
    "http://www.sagaftra.org/",
    "http://www.sagaftra.org/",
    "http://www.taals.net/",
    "http://www.actfl.org/",
    "http://www.afsa.org/",
    "http://www.atanet.org/",
    "http://www.ncte.org/",
    "http://www.historians.org/jobs-and-professional-development/aha-career-center",
    "http://www.nche.net/",
    "https://www.nyhistory.org/web/",
    "http://www.oah.org/",
    "http://www.shafr.org/",
    "https://www.poets.org/",
    "https://www.poets.org/",
    "http://www.copydesk.org/",
    "http://www.asja.org/",
    "http://aaupnet.org/membership/directory.html",
    "http://awpwriter.org/aboutawp/index.htm",
    "http://www.awpwriter.org/careers/overview",
    "http://www.ifwtwa.org/",
    "http://istw-travel.org/",
    "http://www.mla.org/",
    "https://www.spj.org/index.asp",
    "http://www.ams.org/",
    "http://www.amstat.org/index.cfm?fuseaction=main",
    "http://www.maa.org/",
    "http://www.nctm.org/",
    "http://www.siam.org/",
    "http://nursingworld.org/",
    "http://www.oadn.org/",
    "http://www.nysna.org/",
    "http://www.1199seiu.org/",
    "http://www.aapt.org/index.cfm",
    "http://www.aps.org/",
    "http://www.biophysics.org/",
    "http://www.nspe.org/index.html",
    "http://www.apsanet.org/",
    "http://www.isanet.org/",
    "http://aapr-wapr.org/",
    "http://www.acmaweb.org/",
    "http://www.acmaweb.org/",
    "http://www.counseling.org/",
    "http://www.apa.org/",
    "http://www.psychologicalscience.org/",
    "http://www.asapnys.org/",
    "http://www.bacb.com/",
    "http://www.mhaofnyc.org/",
    "http://www.nasponline.org/",
    "http://www.socialworkers.org/",
    "http://www.thenationalcouncil.org/",
    "http://www.siop.org/",
    "http://www.spsp.org/",
    "http://www.asanet.org/",
    "http://www.essnet.org/",
    "http://www.isa-sociology.org/",
    "http://www.aacsnet.net/",
    ]
    

const { type } = require('os');
var request = require('request');

var counter = 0;

for(let i = 0; i < data.length; i++){
    request(data[i], async function (error, response, body) {
        try {
            if(error || response.statusCode > 400){
                counter++;
                console.log("Not Found ", "Index: ", counter , "URL: ", data[i]);
            }
        }

        catch(err) {
            console.log("error")
        }
    })
}




// const express = require('express');
// const request = require("request");

// const app = express();

// app.use((req, res, next) => {
//     res.header('Access-Control-Allow-Origin', '*');
//     next();
// })

// app.get('/jokes/random', (req,res) => {
//     request(
//         {
//             url : 'https://joke-api-strict-cors.appspot.com/jokes/random'
//         },

//         (error, response,body) => {
//             if(error || response.statusCode !== 200) {
//                 return res.status(500).json({type: 'error', message: err.message});
//             }

//             res.json(JSON.parse(body));
//         }
//     )
// });

// const PORT = process.env.PORT || 3001;
// app.listen(PORT, () => console.log(`listening on ${PORT}`));